//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Common", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact info.
        /// </summary>
        internal static string AccountTitle {
            get {
                return ResourceManager.GetString("AccountTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Campaign Code.
        /// </summary>
        internal static string AddCampaignCode {
            get {
                return ResourceManager.GetString("AddCampaignCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address 2.
        /// </summary>
        internal static string Address2 {
            get {
                return ResourceManager.GetString("Address2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to cart.
        /// </summary>
        internal static string AddToCart {
            get {
                return ResourceManager.GetString("AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By clicking Checkout you will be redirected to Adyen to enter your credit card details and will then be returned here..
        /// </summary>
        internal static string AdyenHppDescription {
            get {
                return ResourceManager.GetString("AdyenHppDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card.
        /// </summary>
        internal static string AdyenHppName {
            get {
                return ResourceManager.GetString("AdyenHppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please reload the page and try again..
        /// </summary>
        internal static string AjaxErrorMessage {
            get {
                return ResourceManager.GetString("AjaxErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        internal static string AjaxErrorTitle {
            get {
                return ResourceManager.GetString("AjaxErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount to pay.
        /// </summary>
        internal static string AmountToPay {
            get {
                return ResourceManager.GetString("AmountToPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available packages.
        /// </summary>
        internal static string AvailablePackages {
            get {
                return ResourceManager.GetString("AvailablePackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        internal static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Billing address.
        /// </summary>
        internal static string BillingAddressTitle {
            get {
                return ResourceManager.GetString("BillingAddressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different billing address.
        /// </summary>
        internal static string BillingDifferentThanMain {
            get {
                return ResourceManager.GetString("BillingDifferentThanMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same as contact info.
        /// </summary>
        internal static string BillingSameAsMain {
            get {
                return ResourceManager.GetString("BillingSameAsMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign code.
        /// </summary>
        internal static string CampaignCode {
            get {
                return ResourceManager.GetString("CampaignCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign code sucessfully added.
        /// </summary>
        internal static string CampaignCodeSuccess {
            get {
                return ResourceManager.GetString("CampaignCodeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number.
        /// </summary>
        internal static string CardNumber {
            get {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Owner.
        /// </summary>
        internal static string CardOwner {
            get {
                return ResourceManager.GetString("CardOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVC/CVV.
        /// </summary>
        internal static string CardSecurityCode {
            get {
                return ResourceManager.GetString("CardSecurityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card.
        /// </summary>
        internal static string CCPaymentName {
            get {
                return ResourceManager.GetString("CCPaymentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charged amount.
        /// </summary>
        internal static string ChargedAmount {
            get {
                return ResourceManager.GetString("ChargedAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        internal static string Checkout {
            get {
                return ResourceManager.GetString("Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please go back and add some items to your cart before checking out..
        /// </summary>
        internal static string CheckoutCartIsEmptyDescription {
            get {
                return ResourceManager.GetString("CheckoutCartIsEmptyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your cart is empty.
        /// </summary>
        internal static string CheckoutCartIsEmptyTitle {
            get {
                return ResourceManager.GetString("CheckoutCartIsEmptyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Please try using a different payment method. &lt;/p&gt;
        ///&lt;p&gt;Domain names will be registered after the payment has been verified.&lt;/p&gt;.
        /// </summary>
        internal static string CheckoutFailureDescription {
            get {
                return ResourceManager.GetString("CheckoutFailureDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment was not accepted.
        /// </summary>
        internal static string CheckoutFailureTitle {
            get {
                return ResourceManager.GetString("CheckoutFailureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Your account will be created immediately.&lt;/p&gt;
        ///        	&lt;p&gt;Please check your email for login instructions.&lt;/p&gt;.
        /// </summary>
        internal static string CheckoutSuccessDescription {
            get {
                return ResourceManager.GetString("CheckoutSuccessDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you, and welcome!.
        /// </summary>
        internal static string CheckoutSuccessTitle {
            get {
                return ResourceManager.GetString("CheckoutSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string Company {
            get {
                return ResourceManager.GetString("Company", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporate ID no..
        /// </summary>
        internal static string CompanyIdentityNumber {
            get {
                return ResourceManager.GetString("CompanyIdentityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name.
        /// </summary>
        internal static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected domain.
        /// </summary>
        internal static string ConnectedDomain {
            get {
                return ResourceManager.GetString("ConnectedDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We will set up the services in your package to be connected with the selected domain name..
        /// </summary>
        internal static string ConnectedDomainDescription {
            get {
                return ResourceManager.GetString("ConnectedDomainDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not validate VAT number.
        /// </summary>
        internal static string CouldNotValidateVatNumber {
            get {
                return ResourceManager.GetString("CouldNotValidateVatNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay invoices on expiration day automatically.
        /// </summary>
        internal static string CreditCardAutoPay {
            get {
                return ResourceManager.GetString("CreditCardAutoPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer type.
        /// </summary>
        internal static string CustomerType {
            get {
                return ResourceManager.GetString("CustomerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and Conditions.
        /// </summary>
        internal static string defaultTOS_Name {
            get {
                return ResourceManager.GetString("defaultTOS_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a placeholder for the company&apos;s Terms and Conditions..
        /// </summary>
        internal static string defaultTOS_Terms {
            get {
                return ResourceManager.GetString("defaultTOS_Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German.
        /// </summary>
        internal static string DE_name {
            get {
                return ResourceManager.GetString("DE_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DE.
        /// </summary>
        internal static string DE_shortname {
            get {
                return ResourceManager.GetString("DE_shortname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By clicking Checkout you will be redirected to DIBS to enter your credit card details and will then be returned here..
        /// </summary>
        internal static string DibsFlexwinDescription {
            get {
                return ResourceManager.GetString("DibsFlexwinDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card.
        /// </summary>
        internal static string DibsFlexwinName {
            get {
                return ResourceManager.GetString("DibsFlexwinName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        internal static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss.
        /// </summary>
        internal static string Dismiss {
            get {
                return ResourceManager.GetString("Dismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain.
        /// </summary>
        internal static string Domain {
            get {
                return ResourceManager.GetString("Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is available..
        /// </summary>
        internal static string DomainAvailableHoverTitle {
            get {
                return ResourceManager.GetString("DomainAvailableHoverTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is not available..
        /// </summary>
        internal static string DomainNotAvailableHoverTitle {
            get {
                return ResourceManager.GetString("DomainNotAvailableHoverTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start by picking a domain name for your web hosting package..
        /// </summary>
        internal static string DomainRegistrationDescription {
            get {
                return ResourceManager.GetString("DomainRegistrationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results for.
        /// </summary>
        internal static string DomainRegistrationNoResultsHeading {
            get {
                return ResourceManager.GetString("DomainRegistrationNoResultsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results for.
        /// </summary>
        internal static string DomainRegistrationResultsHeading {
            get {
                return ResourceManager.GetString("DomainRegistrationResultsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not connect a domain.
        /// </summary>
        internal static string DoNotConnectDomain {
            get {
                return ResourceManager.GetString("DoNotConnectDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        internal static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string EN_name {
            get {
                return ResourceManager.GetString("EN_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EN.
        /// </summary>
        internal static string EN_shortname {
            get {
                return ResourceManager.GetString("EN_shortname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid credit card number.
        /// </summary>
        internal static string ErrorCreditCard {
            get {
                return ResourceManager.GetString("ErrorCreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field cannot be empty.
        /// </summary>
        internal static string ErrorEmptyField {
            get {
                return ResourceManager.GetString("ErrorEmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire month must be selected.
        /// </summary>
        internal static string ErrorExpiresMonthRequired {
            get {
                return ResourceManager.GetString("ErrorExpiresMonthRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire year must be selected.
        /// </summary>
        internal static string ErrorExpiresYearRequired {
            get {
                return ResourceManager.GetString("ErrorExpiresYearRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CVC/CVV must be three or four digits.
        /// </summary>
        internal static string ErrorInvalidCardSecurityCode {
            get {
                return ResourceManager.GetString("ErrorInvalidCardSecurityCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid domain name.
        /// </summary>
        internal static string ErrorInvalidDomain {
            get {
                return ResourceManager.GetString("ErrorInvalidDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renewal period format is N-MONTH or N-YEAR.
        /// </summary>
        internal static string ErrorPreselectRenewalPeriod {
            get {
                return ResourceManager.GetString("ErrorPreselectRenewalPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorTermNotChecked.
        /// </summary>
        internal static string ErrorTermNotChecked {
            get {
                return ResourceManager.GetString("ErrorTermNotChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username is not available.
        /// </summary>
        internal static string ErrorUsernameNotAvailable {
            get {
                return ResourceManager.GetString("ErrorUsernameNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you do not have enough privileges to view the page..
        /// </summary>
        internal static string Error_ForbiddenDescription {
            get {
                return ResourceManager.GetString("Error_ForbiddenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forbidden.
        /// </summary>
        internal static string Error_ForbiddenTitle {
            get {
                return ResourceManager.GetString("Error_ForbiddenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error has occurred. Please try again later..
        /// </summary>
        internal static string Error_InternalServerErrorDescription {
            get {
                return ResourceManager.GetString("Error_InternalServerErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        internal static string Error_InternalServerErrorTitle {
            get {
                return ResourceManager.GetString("Error_InternalServerErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The resource you were looking for is not here..
        /// </summary>
        internal static string Error_NotFoundDescription {
            get {
                return ResourceManager.GetString("Error_NotFoundDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        internal static string Error_NotFoundTitle {
            get {
                return ResourceManager.GetString("Error_NotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expires.
        /// </summary>
        internal static string Expires {
            get {
                return ResourceManager.GetString("Expires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expires, month.
        /// </summary>
        internal static string ExpiresMonth {
            get {
                return ResourceManager.GetString("ExpiresMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expires, year.
        /// </summary>
        internal static string ExpiresYear {
            get {
                return ResourceManager.GetString("ExpiresYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax.
        /// </summary>
        internal static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee.
        /// </summary>
        internal static string Fee {
            get {
                return ResourceManager.GetString("Fee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find domain.
        /// </summary>
        internal static string FindDomain {
            get {
                return ResourceManager.GetString("FindDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to French.
        /// </summary>
        internal static string FR_name {
            get {
                return ResourceManager.GetString("FR_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FR.
        /// </summary>
        internal static string FR_shortname {
            get {
                return ResourceManager.GetString("FR_shortname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string HostingPackageDescription {
            get {
                return ResourceManager.GetString("HostingPackageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select your web hosting package.
        /// </summary>
        internal static string HostingPackageTitle {
            get {
                return ResourceManager.GetString("HostingPackageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual.
        /// </summary>
        internal static string Individual {
            get {
                return ResourceManager.GetString("Individual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal ID no..
        /// </summary>
        internal static string IndividualIdentityNumber {
            get {
                return ResourceManager.GetString("IndividualIdentityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid VAT number.
        /// </summary>
        internal static string InvalidVatNumber {
            get {
                return ResourceManager.GetString("InvalidVatNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        internal static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string InvoiceByEmailName {
            get {
                return ResourceManager.GetString("InvoiceByEmailName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        internal static string InvoiceByPostName {
            get {
                return ResourceManager.GetString("InvoiceByPostName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string Item {
            get {
                return ResourceManager.GetString("Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string LanguageSelectorTitle {
            get {
                return ResourceManager.GetString("LanguageSelectorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        internal static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to month.
        /// </summary>
        internal static string MONTH {
            get {
                return ResourceManager.GetString("MONTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to months.
        /// </summary>
        internal static string MONTHPlural {
            get {
                return ResourceManager.GetString("MONTHPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More results.
        /// </summary>
        internal static string MoreResults {
            get {
                return ResourceManager.GetString("MoreResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No VAT.
        /// </summary>
        internal static string NoTax {
            get {
                return ResourceManager.GetString("NoTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer has no VATnumber.
        /// </summary>
        internal static string NoVatNumber {
            get {
                return ResourceManager.GetString("NoVatNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order web hosting and DNS.
        /// </summary>
        internal static string OrderPageTitle {
            get {
                return ResourceManager.GetString("OrderPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By clicking Checkout you will be redirected to PayEx to enter your credit card details and will then be returned here..
        /// </summary>
        internal static string PayExRedirectDescription {
            get {
                return ResourceManager.GetString("PayExRedirectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card.
        /// </summary>
        internal static string PayExRedirectName {
            get {
                return ResourceManager.GetString("PayExRedirectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment options.
        /// </summary>
        internal static string PaymentOptions {
            get {
                return ResourceManager.GetString("PaymentOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment profile options.
        /// </summary>
        internal static string PaymentProfileOptions {
            get {
                return ResourceManager.GetString("PaymentProfileOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;We are ready to take your order now. Please review your order and click on Order button to confirm the transaction. &lt;/p&gt;
        ///&lt;p&gt;Your order will be securely processed by PayPal.&lt;/p&gt;.
        /// </summary>
        internal static string PayPalConfirmDescription {
            get {
                return ResourceManager.GetString("PayPalConfirmDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayPal confirmation.
        /// </summary>
        internal static string PayPalConfirmTitle {
            get {
                return ResourceManager.GetString("PayPalConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By clicking Checkout you will be redirected to PayPal to enter your credentials or credit card details and will then be returned here to finish the transaction..
        /// </summary>
        internal static string PayPalDescription {
            get {
                return ResourceManager.GetString("PayPalDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PayPal.
        /// </summary>
        internal static string PayPalName {
            get {
                return ResourceManager.GetString("PayPalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay using.
        /// </summary>
        internal static string PayUsing {
            get {
                return ResourceManager.GetString("PayUsing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        internal static string PayWithInvoiceName {
            get {
                return ResourceManager.GetString("PayWithInvoiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period.
        /// </summary>
        internal static string Period {
            get {
                return ResourceManager.GetString("Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {1} {2} - {0}.
        /// </summary>
        internal static string PricingVariantDisplay {
            get {
                return ResourceManager.GetString("PricingVariantDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (from {1} to {2} {3}) - {4}.
        /// </summary>
        internal static string PricingVariantUBPDisplay {
            get {
                return ResourceManager.GetString("PricingVariantUBPDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have read and agree with the.
        /// </summary>
        internal static string ReadAndAgree {
            get {
                return ResourceManager.GetString("ReadAndAgree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        internal static string RenewalPeriodDisplay {
            get {
                return ResourceManager.GetString("RenewalPeriodDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        internal static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make it same as contact info.
        /// </summary>
        internal static string SameAsContactInfo {
            get {
                return ResourceManager.GetString("SameAsContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save my credit card information.
        /// </summary>
        internal static string SaveCreditCardInfo {
            get {
                return ResourceManager.GetString("SaveCreditCardInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SelectMonth {
            get {
                return ResourceManager.GetString("SelectMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SelectYear {
            get {
                return ResourceManager.GetString("SelectYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send invoice via.
        /// </summary>
        internal static string SendInvoiceVia {
            get {
                return ResourceManager.GetString("SendInvoiceVia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shopping cart.
        /// </summary>
        internal static string ShoppingCart {
            get {
                return ResourceManager.GetString("ShoppingCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items in your shopping cart can be removed..
        /// </summary>
        internal static string ShoppingCartDescription {
            get {
                return ResourceManager.GetString("ShoppingCartDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no items in the shopping cart..
        /// </summary>
        internal static string ShoppingCartEmpty {
            get {
                return ResourceManager.GetString("ShoppingCartEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue without adding a domain name.
        /// </summary>
        internal static string SkipDomain {
            get {
                return ResourceManager.GetString("SkipDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up account info.
        /// </summary>
        internal static string StepDescriptionAccount {
            get {
                return ResourceManager.GetString("StepDescriptionAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice and payment options.
        /// </summary>
        internal static string StepDescriptionCheckout {
            get {
                return ResourceManager.GetString("StepDescriptionCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy new or move existing.
        /// </summary>
        internal static string StepDescriptionDomains {
            get {
                return ResourceManager.GetString("StepDescriptionDomains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose hosting package.
        /// </summary>
        internal static string StepDescriptionHostingPackage {
            get {
                return ResourceManager.GetString("StepDescriptionHostingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string StepTitleAccount {
            get {
                return ResourceManager.GetString("StepTitleAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        internal static string StepTitleCheckout {
            get {
                return ResourceManager.GetString("StepTitleCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domains.
        /// </summary>
        internal static string StepTitleDomains {
            get {
                return ResourceManager.GetString("StepTitleDomains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hosting.
        /// </summary>
        internal static string StepTitleHostingPackage {
            get {
                return ResourceManager.GetString("StepTitleHostingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal.
        /// </summary>
        internal static string Subtotal {
            get {
                return ResourceManager.GetString("Subtotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Swedish.
        /// </summary>
        internal static string SV_SE_name {
            get {
                return ResourceManager.GetString("SV_SE_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE.
        /// </summary>
        internal static string SV_SE_shortname {
            get {
                return ResourceManager.GetString("SV_SE_shortname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taken.
        /// </summary>
        internal static string Taken {
            get {
                return ResourceManager.GetString("Taken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT.
        /// </summary>
        internal static string Tax {
            get {
                return ResourceManager.GetString("Tax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT {0}.
        /// </summary>
        internal static string TaxNameDisplay {
            get {
                return ResourceManager.GetString("TaxNameDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms.
        /// </summary>
        internal static string Terms {
            get {
                return ResourceManager.GetString("Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CORE&apos;s Terms and Conditions.
        /// </summary>
        internal static string TOS_core_Name {
            get {
                return ResourceManager.GetString("TOS_core_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a placeholder for the company&apos;s Terms and Conditions..
        /// </summary>
        internal static string TOS_core_Terms {
            get {
                return ResourceManager.GetString("TOS_core_Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and Conditions for .SE domain names.
        /// </summary>
        internal static string TOS_se_Name {
            get {
                return ResourceManager.GetString("TOS_se_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is a placeholder for the company&apos;s Terms and Conditions..
        /// </summary>
        internal static string TOS_se_Terms {
            get {
                return ResourceManager.GetString("TOS_se_Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again.
        /// </summary>
        internal static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validating.
        /// </summary>
        internal static string Validating {
            get {
                return ResourceManager.GetString("Validating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT number.
        /// </summary>
        internal static string VatNumber {
            get {
                return ResourceManager.GetString("VatNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your VAT number in not correct or the validation service is not available at the moment, therefore VAT will be applied to your invoice. You should check your VAT number and try to validate it again..
        /// </summary>
        internal static string VatNumberWarning {
            get {
                return ResourceManager.GetString("VatNumberWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VAT validation successful.
        /// </summary>
        internal static string VatValidationSuccessTitle {
            get {
                return ResourceManager.GetString("VatValidationSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your VAT number is successfully validated and your invoice will be free of VAT..
        /// </summary>
        internal static string VatValidationSucessDescription {
            get {
                return ResourceManager.GetString("VatValidationSucessDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHOIS contact.
        /// </summary>
        internal static string WhoisAddressTitle {
            get {
                return ResourceManager.GetString("WhoisAddressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Different WHOIS contact.
        /// </summary>
        internal static string WhoisDifferentThanMain {
            get {
                return ResourceManager.GetString("WhoisDifferentThanMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Same as contact info.
        /// </summary>
        internal static string WhoisSameAsMain {
            get {
                return ResourceManager.GetString("WhoisSameAsMain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By clicking Checkout you will be redirected to Worldpay to enter your credit card details and will then be returned here..
        /// </summary>
        internal static string WorldPayRedirectDescription {
            get {
                return ResourceManager.GetString("WorldPayRedirectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card.
        /// </summary>
        internal static string WorldPayRedirectName {
            get {
                return ResourceManager.GetString("WorldPayRedirectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By clicking Checkout you will be redirected to Worldpay to enter your credit card details and will then be returned here..
        /// </summary>
        internal static string WorldPayXmlRedirectDescription {
            get {
                return ResourceManager.GetString("WorldPayXmlRedirectDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Card.
        /// </summary>
        internal static string WorldPayXmlRedirectName {
            get {
                return ResourceManager.GetString("WorldPayXmlRedirectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to year.
        /// </summary>
        internal static string YEAR {
            get {
                return ResourceManager.GetString("YEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to years.
        /// </summary>
        internal static string YEARPlural {
            get {
                return ResourceManager.GetString("YEARPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip.
        /// </summary>
        internal static string Zip {
            get {
                return ResourceManager.GetString("Zip", resourceCulture);
            }
        }
    }
}
