//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CustomFields {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomFields() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CustomFields", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENS identifier.
        /// </summary>
        internal static string aero_ens_id {
            get {
                return ResourceManager.GetString("aero_ens_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENS password.
        /// </summary>
        internal static string aero_ens_password {
            get {
                return ResourceManager.GetString("aero_ens_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coop verification code.
        /// </summary>
        internal static string coop_verification_code {
            get {
                return ResourceManager.GetString("coop_verification_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth country code (2-letter).
        /// </summary>
        internal static string country_of_birth {
            get {
                return ResourceManager.GetString("country_of_birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use ISO3166 two-letter country code.
        /// </summary>
        internal static string country_of_birth_default_default_dmn_fr {
            get {
                return ResourceManager.GetString("country_of_birth.default.default.dmn-fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use ISO3166 two-letter country code.
        /// </summary>
        internal static string country_of_birth_default_default_dmn_pm {
            get {
                return ResourceManager.GetString("country_of_birth.default.default.dmn-pm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use ISO3166 two-letter country code.
        /// </summary>
        internal static string country_of_birth_default_default_dmn_re {
            get {
                return ResourceManager.GetString("country_of_birth.default.default.dmn-re", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use ISO3166 two-letter country code.
        /// </summary>
        internal static string country_of_birth_default_default_dmn_tf {
            get {
                return ResourceManager.GetString("country_of_birth.default.default.dmn-tf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use ISO3166 two-letter country code.
        /// </summary>
        internal static string country_of_birth_default_default_dmn_wf {
            get {
                return ResourceManager.GetString("country_of_birth.default.default.dmn-wf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use ISO3166 two-letter country code.
        /// </summary>
        internal static string country_of_birth_default_default_dmn_yt {
            get {
                return ResourceManager.GetString("country_of_birth.default.default.dmn-yt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth (YYYY-MM-DD).
        /// </summary>
        internal static string date_of_birth {
            get {
                return ResourceManager.GetString("date_of_birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use date format: YYYY-MM-DD.
        /// </summary>
        internal static string date_of_birth_default_default_dmn_fr {
            get {
                return ResourceManager.GetString("date_of_birth.default.default.dmn-fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use date format: YYYY-MM-DD.
        /// </summary>
        internal static string date_of_birth_default_default_dmn_hk {
            get {
                return ResourceManager.GetString("date_of_birth.default.default.dmn-hk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use date format: YYYY-MM-DD.
        /// </summary>
        internal static string date_of_birth_default_default_dmn_pm {
            get {
                return ResourceManager.GetString("date_of_birth.default.default.dmn-pm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use date format: YYYY-MM-DD.
        /// </summary>
        internal static string date_of_birth_default_default_dmn_re {
            get {
                return ResourceManager.GetString("date_of_birth.default.default.dmn-re", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use date format: YYYY-MM-DD.
        /// </summary>
        internal static string date_of_birth_default_default_dmn_ru {
            get {
                return ResourceManager.GetString("date_of_birth.default.default.dmn-ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use date format: YYYY-MM-DD.
        /// </summary>
        internal static string date_of_birth_default_default_dmn_tf {
            get {
                return ResourceManager.GetString("date_of_birth.default.default.dmn-tf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use date format: YYYY-MM-DD.
        /// </summary>
        internal static string date_of_birth_default_default_dmn_wf {
            get {
                return ResourceManager.GetString("date_of_birth.default.default.dmn-wf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use date format: YYYY-MM-DD.
        /// </summary>
        internal static string date_of_birth_default_default_dmn_yt {
            get {
                return ResourceManager.GetString("date_of_birth.default.default.dmn-yt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eligibility document ID.
        /// </summary>
        internal static string eligibility_id {
            get {
                return ResourceManager.GetString("eligibility_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eligibility ID type.
        /// </summary>
        internal static string eligibility_id_type {
            get {
                return ResourceManager.GetString("eligibility_id_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values can be: ABN, ACT BN, NSW BN, NT BN, QLD BN, SA BN, TAS BN, VIC BN, WA BN, ACN or OTHER.
        /// </summary>
        internal static string eligibility_id_type_default_default_dmn_asnau {
            get {
                return ResourceManager.GetString("eligibility_id_type.default.default.dmn-asnau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values can be: ABN, ACN, TM or OTHER.
        /// </summary>
        internal static string eligibility_id_type_default_default_dmn_comau {
            get {
                return ResourceManager.GetString("eligibility_id_type.default.default.dmn-comau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values can be: ABN, ACN, TM or OTHER.
        /// </summary>
        internal static string eligibility_id_type_default_default_dmn_netau {
            get {
                return ResourceManager.GetString("eligibility_id_type.default.default.dmn-netau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values can be: ABN, ACT BN, NSW BN, NT BN, QLD BN, SA BN, TAS BN, VIC BN, WA BN, ACN or OTHER.
        /// </summary>
        internal static string eligibility_id_type_default_default_dmn_orgau {
            get {
                return ResourceManager.GetString("eligibility_id_type.default.default.dmn-orgau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name on eligibility doc..
        /// </summary>
        internal static string eligibility_name {
            get {
                return ResourceManager.GetString("eligibility_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eligibility type.
        /// </summary>
        internal static string eligibility_type {
            get {
                return ResourceManager.GetString("eligibility_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values can be: Charity, Club, Incorporated Association, Non-profit Organization or Trade Union.
        /// </summary>
        internal static string eligibility_type_default_default_dmn_asnau {
            get {
                return ResourceManager.GetString("eligibility_type.default.default.dmn-asnau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values can be: Company, Partnership, Pending TM Owner, Registered Business or Trademark Owner.
        /// </summary>
        internal static string eligibility_type_default_default_dmn_comau {
            get {
                return ResourceManager.GetString("eligibility_type.default.default.dmn-comau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values can be: Company, Partnership, Pending TM Owner, Registered Business or Trademark Owner.
        /// </summary>
        internal static string eligibility_type_default_default_dmn_netau {
            get {
                return ResourceManager.GetString("eligibility_type.default.default.dmn-netau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values can be: Charity, Club, Incorporated Association, Non-profit Organization or Trade Union.
        /// </summary>
        internal static string eligibility_type_default_default_dmn_orgau {
            get {
                return ResourceManager.GetString("eligibility_type.default.default.dmn-orgau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal entity type of registrant.
        /// </summary>
        internal static string entity_type {
            get {
                return ResourceManager.GetString("entity_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values can be: 1(individual), 2(company), 3(freelancers), 4(Non-profit org.), 5(Public org.), 6(other), 7(Non-italian that match 2-6).
        /// </summary>
        internal static string entity_type_default_default_dmn_it {
            get {
                return ResourceManager.GetString("entity_type.default.default.dmn-it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Individual.
        /// </summary>
        internal static string entity_type_default_default_dmn_it_1 {
            get {
                return ResourceManager.GetString("entity_type.default.default.dmn-it.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company.
        /// </summary>
        internal static string entity_type_default_default_dmn_it_2 {
            get {
                return ResourceManager.GetString("entity_type.default.default.dmn-it.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freelancers.
        /// </summary>
        internal static string entity_type_default_default_dmn_it_3 {
            get {
                return ResourceManager.GetString("entity_type.default.default.dmn-it.3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-profit organization.
        /// </summary>
        internal static string entity_type_default_default_dmn_it_4 {
            get {
                return ResourceManager.GetString("entity_type.default.default.dmn-it.4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Public organization.
        /// </summary>
        internal static string entity_type_default_default_dmn_it_5 {
            get {
                return ResourceManager.GetString("entity_type.default.default.dmn-it.5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        internal static string entity_type_default_default_dmn_it_6 {
            get {
                return ResourceManager.GetString("entity_type.default.default.dmn-it.6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-italian that match 2-6.
        /// </summary>
        internal static string entity_type_default_default_dmn_it_7 {
            get {
                return ResourceManager.GetString("entity_type.default.default.dmn-it.7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID card issuer.
        /// </summary>
        internal static string id_card_authority {
            get {
                return ResourceManager.GetString("id_card_authority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID card issue date.
        /// </summary>
        internal static string id_card_issue_date {
            get {
                return ResourceManager.GetString("id_card_issue_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use date format: YYYY-MM-DD.
        /// </summary>
        internal static string id_card_issue_date_default_default_dmn_ru {
            get {
                return ResourceManager.GetString("id_card_issue_date.default.default.dmn-ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact ID type.
        /// </summary>
        internal static string id_type {
            get {
                return ResourceManager.GetString("id_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values can be: passport, certificate, legislation, societyRegistry or politicalPartyRegistry.
        /// </summary>
        internal static string id_type_default_default_dmn_asia {
            get {
                return ResourceManager.GetString("id_type.default.default.dmn-asia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate.
        /// </summary>
        internal static string id_type_default_default_dmn_asia_certificate {
            get {
                return ResourceManager.GetString("id_type.default.default.dmn-asia.certificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legislation.
        /// </summary>
        internal static string id_type_default_default_dmn_asia_legislation {
            get {
                return ResourceManager.GetString("id_type.default.default.dmn-asia.legislation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport.
        /// </summary>
        internal static string id_type_default_default_dmn_asia_passport {
            get {
                return ResourceManager.GetString("id_type.default.default.dmn-asia.passport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Political Party Registry.
        /// </summary>
        internal static string id_type_default_default_dmn_asia_politicalPartyRegistry {
            get {
                return ResourceManager.GetString("id_type.default.default.dmn-asia.politicalPartyRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Society Registry.
        /// </summary>
        internal static string id_type_default_default_dmn_asia_societyRegistry {
            get {
                return ResourceManager.GetString("id_type.default.default.dmn-asia.societyRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member of SHRM(Yes/No).
        /// </summary>
        internal static string jobs_association_member {
            get {
                return ResourceManager.GetString("jobs_association_member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values can be: Yes or No.
        /// </summary>
        internal static string jobs_association_member_default_default_dmn_jobs {
            get {
                return ResourceManager.GetString("jobs_association_member.default.default.dmn-jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company website.
        /// </summary>
        internal static string jobs_website {
            get {
                return ResourceManager.GetString("jobs_website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website link not valid.
        /// </summary>
        internal static string jobs_website_default_default_dmn_jobs {
            get {
                return ResourceManager.GetString("jobs_website.default.default.dmn-jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legal entity type.
        /// </summary>
        internal static string legal_entity_type {
            get {
                return ResourceManager.GetString("legal_entity_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values can be: naturalPerson, corporation, cooperative, partnership, government, politicalParty, society or institution.
        /// </summary>
        internal static string legal_entity_type_default_default_dmn_asia {
            get {
                return ResourceManager.GetString("legal_entity_type.default.default.dmn-asia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooperative.
        /// </summary>
        internal static string legal_entity_type_default_default_dmn_asia_cooperative {
            get {
                return ResourceManager.GetString("legal_entity_type.default.default.dmn-asia.cooperative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corporation.
        /// </summary>
        internal static string legal_entity_type_default_default_dmn_asia_corporation {
            get {
                return ResourceManager.GetString("legal_entity_type.default.default.dmn-asia.corporation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government.
        /// </summary>
        internal static string legal_entity_type_default_default_dmn_asia_government {
            get {
                return ResourceManager.GetString("legal_entity_type.default.default.dmn-asia.government", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institution.
        /// </summary>
        internal static string legal_entity_type_default_default_dmn_asia_institution {
            get {
                return ResourceManager.GetString("legal_entity_type.default.default.dmn-asia.institution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Natural Person.
        /// </summary>
        internal static string legal_entity_type_default_default_dmn_asia_naturalPerson {
            get {
                return ResourceManager.GetString("legal_entity_type.default.default.dmn-asia.naturalPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partnership.
        /// </summary>
        internal static string legal_entity_type_default_default_dmn_asia_partnership {
            get {
                return ResourceManager.GetString("legal_entity_type.default.default.dmn-asia.partnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Political Party.
        /// </summary>
        internal static string legal_entity_type_default_default_dmn_asia_politicalParty {
            get {
                return ResourceManager.GetString("legal_entity_type.default.default.dmn-asia.politicalParty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Society.
        /// </summary>
        internal static string legal_entity_type_default_default_dmn_asia_society {
            get {
                return ResourceManager.GetString("legal_entity_type.default.default.dmn-asia.society", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application purpose.
        /// </summary>
        internal static string nexus_app_purpose {
            get {
                return ResourceManager.GetString("nexus_app_purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application purpose can be P1, P2, P3, P4 or P5.
        /// </summary>
        internal static string nexus_app_purpose_default_default_dmn_us {
            get {
                return ResourceManager.GetString("nexus_app_purpose.default.default.dmn-us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nexus category.
        /// </summary>
        internal static string nexus_category {
            get {
                return ResourceManager.GetString("nexus_category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nexus category can be C11, C12, C21, C31 or C32.
        /// </summary>
        internal static string nexus_category_default_default_dmn_us {
            get {
                return ResourceManager.GetString("nexus_category.default.default.dmn-us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City of birth.
        /// </summary>
        internal static string place_of_birth {
            get {
                return ResourceManager.GetString("place_of_birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason for a domain.
        /// </summary>
        internal static string policy_reason {
            get {
                return ResourceManager.GetString("policy_reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values can be: 1 (exact match) or 2 (closely connected). Default: 2.
        /// </summary>
        internal static string policy_reason_default_default_dmn_asnau {
            get {
                return ResourceManager.GetString("policy_reason.default.default.dmn-asnau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exact match.
        /// </summary>
        internal static string policy_reason_default_default_dmn_asnau_1 {
            get {
                return ResourceManager.GetString("policy_reason.default.default.dmn-asnau.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closely connected.
        /// </summary>
        internal static string policy_reason_default_default_dmn_asnau_2 {
            get {
                return ResourceManager.GetString("policy_reason.default.default.dmn-asnau.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values can be: 1 (exact match) or 2 (closely connected). Default: 2.
        /// </summary>
        internal static string policy_reason_default_default_dmn_comau {
            get {
                return ResourceManager.GetString("policy_reason.default.default.dmn-comau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exact match.
        /// </summary>
        internal static string policy_reason_default_default_dmn_comau_1 {
            get {
                return ResourceManager.GetString("policy_reason.default.default.dmn-comau.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closely connected.
        /// </summary>
        internal static string policy_reason_default_default_dmn_comau_2 {
            get {
                return ResourceManager.GetString("policy_reason.default.default.dmn-comau.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values can be: 1 (exact match) or 2 (closely connected). Default: 2.
        /// </summary>
        internal static string policy_reason_default_default_dmn_idau {
            get {
                return ResourceManager.GetString("policy_reason.default.default.dmn-idau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exact match.
        /// </summary>
        internal static string policy_reason_default_default_dmn_idau_1 {
            get {
                return ResourceManager.GetString("policy_reason.default.default.dmn-idau.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closely connected.
        /// </summary>
        internal static string policy_reason_default_default_dmn_idau_2 {
            get {
                return ResourceManager.GetString("policy_reason.default.default.dmn-idau.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values can be: 1 (exact match) or 2 (closely connected). Default: 2.
        /// </summary>
        internal static string policy_reason_default_default_dmn_netau {
            get {
                return ResourceManager.GetString("policy_reason.default.default.dmn-netau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exact match.
        /// </summary>
        internal static string policy_reason_default_default_dmn_netau_1 {
            get {
                return ResourceManager.GetString("policy_reason.default.default.dmn-netau.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closely connected.
        /// </summary>
        internal static string policy_reason_default_default_dmn_netau_2 {
            get {
                return ResourceManager.GetString("policy_reason.default.default.dmn-netau.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values can be: 1 (exact match) or 2 (closely connected). Default: 2.
        /// </summary>
        internal static string policy_reason_default_default_dmn_orgau {
            get {
                return ResourceManager.GetString("policy_reason.default.default.dmn-orgau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exact match.
        /// </summary>
        internal static string policy_reason_default_default_dmn_orgau_1 {
            get {
                return ResourceManager.GetString("policy_reason.default.default.dmn-orgau.1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closely connected.
        /// </summary>
        internal static string policy_reason_default_default_dmn_orgau_2 {
            get {
                return ResourceManager.GetString("policy_reason.default.default.dmn-orgau.2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth place postal code.
        /// </summary>
        internal static string postal_code_of_birth {
            get {
                return ResourceManager.GetString("postal_code_of_birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profession.
        /// </summary>
        internal static string profession {
            get {
                return ResourceManager.GetString("profession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Province of birth.
        /// </summary>
        internal static string province_of_birth {
            get {
                return ResourceManager.GetString("province_of_birth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrant ID type.
        /// </summary>
        internal static string registrant_id_type {
            get {
                return ResourceManager.GetString("registrant_id_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values can be: ACN or ABN.
        /// </summary>
        internal static string registrant_id_type_default_default_dmn_asnau {
            get {
                return ResourceManager.GetString("registrant_id_type.default.default.dmn-asnau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values can be: ACN or ABN.
        /// </summary>
        internal static string registrant_id_type_default_default_dmn_comau {
            get {
                return ResourceManager.GetString("registrant_id_type.default.default.dmn-comau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values can be: ACN or ABN.
        /// </summary>
        internal static string registrant_id_type_default_default_dmn_idau {
            get {
                return ResourceManager.GetString("registrant_id_type.default.default.dmn-idau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values can be: ACN or ABN.
        /// </summary>
        internal static string registrant_id_type_default_default_dmn_netau {
            get {
                return ResourceManager.GetString("registrant_id_type.default.default.dmn-netau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values can be: ACN or ABN.
        /// </summary>
        internal static string registrant_id_type_default_default_dmn_orgau {
            get {
                return ResourceManager.GetString("registrant_id_type.default.default.dmn-orgau", resourceCulture);
            }
        }
    }
}
