//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CustomerValidation {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomerValidation() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.CustomerValidation", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address is not valid.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The city is not valid.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The corporate ID no. is not valid.
        /// </summary>
        internal static string CompanyIdentityNumber {
            get {
                return ResourceManager.GetString("CompanyIdentityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The company name is not valid.
        /// </summary>
        internal static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The country is not valid.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The email address is not valid.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The fax number is not valid for the selected country.
        /// </summary>
        internal static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first name is not valid.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The company/person no. is not valid.
        /// </summary>
        internal static string IdentityNumber {
            get {
                return ResourceManager.GetString("IdentityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid Norwegian identity number (YYMMDD-XXXXX).
        /// </summary>
        internal static string identity_number_no_default_default {
            get {
                return ResourceManager.GetString("identity_number.no.default.default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid Swedish identity number (YYMMDD-XXXX).
        /// </summary>
        internal static string identity_number_se_default_default {
            get {
                return ResourceManager.GetString("identity_number.se.default.default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .nu domain order requires a Swedish company/person no..
        /// </summary>
        internal static string identity_number_se_default_dmn_nu {
            get {
                return ResourceManager.GetString("identity_number.se.default.dmn-nu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .se domain order requires a Swedish company/person no..
        /// </summary>
        internal static string identity_number_se_default_dmn_se {
            get {
                return ResourceManager.GetString("identity_number.se.default.dmn-se", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The personal ID no. is not valid.
        /// </summary>
        internal static string IndividualIdentityNumber {
            get {
                return ResourceManager.GetString("IndividualIdentityNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last name is not valid.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The mobile number is not valid for the selected country.
        /// </summary>
        internal static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone number is not valid for the selected country.
        /// </summary>
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must read and accept the Terms and Conditions.
        /// </summary>
        internal static string TermsConfirmation {
            get {
                return ResourceManager.GetString("TermsConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The VAT number is not valid for the selected country.
        /// </summary>
        internal static string VatNumber {
            get {
                return ResourceManager.GetString("VatNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .nu domain order requires a valid VAT number.
        /// </summary>
        internal static string vat_number_default_default_dmn_nu {
            get {
                return ResourceManager.GetString("vat_number.default.default.dmn-nu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .se domain order requires a valid VAT number.
        /// </summary>
        internal static string vat_number_default_default_dmn_se {
            get {
                return ResourceManager.GetString("vat_number.default.default.dmn-se", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The zip is not valid for the selected country.
        /// </summary>
        internal static string Zip {
            get {
                return ResourceManager.GetString("Zip", resourceCulture);
            }
        }
    }
}
