//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ValidationErrors", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The domain name allready exists in the system.
        /// </summary>
        internal static string DomainExists {
            get {
                return ResourceManager.GetString("DomainExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To view Self Declaration Form you must fill in the fields:.
        /// </summary>
        internal static string ErrorDeclarationFill {
            get {
                return ResourceManager.GetString("ErrorDeclarationFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must read and accept the Declaration.
        /// </summary>
        internal static string ErrorDeclarationNotChecked {
            get {
                return ResourceManager.GetString("ErrorDeclarationNotChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field cannot be empty.
        /// </summary>
        internal static string ErrorEmptyField {
            get {
                return ResourceManager.GetString("ErrorEmptyField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid characters.
        /// </summary>
        internal static string ErrorInvalidChars {
            get {
                return ResourceManager.GetString("ErrorInvalidChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid domain name.
        /// </summary>
        internal static string ErrorInvalidDomain {
            get {
                return ResourceManager.GetString("ErrorInvalidDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more domain names are invalid.
        /// </summary>
        internal static string ErrorInvalidDomains {
            get {
                return ResourceManager.GetString("ErrorInvalidDomains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid E-mail address.
        /// </summary>
        internal static string ErrorInvalidEmail {
            get {
                return ResourceManager.GetString("ErrorInvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format.
        /// </summary>
        internal static string ErrorInvalidFormat {
            get {
                return ResourceManager.GetString("ErrorInvalidFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid format, expected 10 digits.
        /// </summary>
        internal static string ErrorInvalidOrgNumber {
            get {
                return ResourceManager.GetString("ErrorInvalidOrgNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid post number.
        /// </summary>
        internal static string ErrorInvalidPostNumber {
            get {
                return ResourceManager.GetString("ErrorInvalidPostNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subdomain name is not valid..
        /// </summary>
        internal static string ErrorInvalidSubdomain {
            get {
                return ResourceManager.GetString("ErrorInvalidSubdomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid European VAT number.
        /// </summary>
        internal static string ErrorInvalidVATNumber {
            get {
                return ResourceManager.GetString("ErrorInvalidVATNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only single level subdomains allowed..
        /// </summary>
        internal static string ErrorMultiLevelSubdomain {
            get {
                return ResourceManager.GetString("ErrorMultiLevelSubdomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to be company or organization.
        /// </summary>
        internal static string ErrorMustBeCompany {
            get {
                return ResourceManager.GetString("ErrorMustBeCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have a EU address in order to register a .eu domain..
        /// </summary>
        internal static string ErrorMustBeFromEU {
            get {
                return ResourceManager.GetString("ErrorMustBeFromEU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have a German address in order to register a .de domain..
        /// </summary>
        internal static string ErrorMustBeFromGermany {
            get {
                return ResourceManager.GetString("ErrorMustBeFromGermany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have a Dutch address in order to register a .nl domain..
        /// </summary>
        internal static string ErrorMustBeFromNetherlands {
            get {
                return ResourceManager.GetString("ErrorMustBeFromNetherlands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must have a Norwegian address in order to register a .no domain..
        /// </summary>
        internal static string ErrorMustBeFromNorway {
            get {
                return ResourceManager.GetString("ErrorMustBeFromNorway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a domain name.
        /// </summary>
        internal static string ErrorNoDomain {
            get {
                return ResourceManager.GetString("ErrorNoDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximimum number of domain names has been exeeded.
        /// </summary>
        internal static string ErrorNumDomains {
            get {
                return ResourceManager.GetString("ErrorNumDomains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid organization number/civic personal number.
        /// </summary>
        internal static string ErrorOrgNumberCheckSum {
            get {
                return ResourceManager.GetString("ErrorOrgNumberCheckSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while processing.
        /// </summary>
        internal static string ErrorProcessing {
            get {
                return ResourceManager.GetString("ErrorProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add up to 4 domain names separated by space.
        /// </summary>
        internal static string ErrorSearchArguments {
            get {
                return ResourceManager.GetString("ErrorSearchArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of characters has been exeeded.
        /// </summary>
        internal static string ErrorStringLength {
            get {
                return ResourceManager.GetString("ErrorStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must read and accept the Terms of Service.
        /// </summary>
        internal static string ErrorTermNotChecked {
            get {
                return ResourceManager.GetString("ErrorTermNotChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The username is not available.
        /// </summary>
        internal static string ErrorUsernameNotAvailable {
            get {
                return ResourceManager.GetString("ErrorUsernameNotAvailable", resourceCulture);
            }
        }
    }
}
